### ISSUE TITLE
[Plan] MediaCreation as a landing page

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-MediaCreation#57]
## What

Produce working, tested examples of OpenAssetIO + MediaCreation covering common post-production asset management tasks.
These should use the tooling/approach determined by https://github.com/OpenAssetIO/OpenAssetIO/issues/946.

## Why

- Help people understand what this thing actually does
- Help people get started with usage of  the libraries
```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/59
```

**Comment by elliotcmorris** [comment]
No need to track this as it stands.
