### ISSUE TITLE
Consider recommending vendoring MediaCreation

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-MediaCreation#61]
To effectively make it a private dependency.

Related to #64

**Comment by elliotcmorris** [comment]
Effectively part of https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/61, and whether this remains a thing will depend on the outcome of that.

**Comment by SamCrooksFoundry** [comment]
Whilst doing this would solve compatibility issues, it would be very unfriendly for users.  We are closing this for now as it's not a near term issue. We would prefer to solve this by using custom namespaces.
