### ISSUE TITLE
[Investigation] Trait/Specification versioning strategies

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO-MediaCreation#73]
## What 

Investigate versioning strategies for traits and specifications in a shareable form for wider community discussion.

Consider
* Whole-package vs. individual traits
* Upgrading vs downgrading vs. neither, and its mechanism. Also whether upgrade/downgrade functions can be deferred til later.
* Host vs. manager introspection/responsibility
* Version format/comparison
* The effect of vendoring trait view libraries (e.g. MediaCreation) vs. global per-application.

## Acceptance criteria

DR(s) with
* Research on prior art
* Possible options

**Comment by elliotcmorris** [comment]
This got away from us. The idea that we're gonna be able to make this decision in one DR dosen't seem possible, there's too many overlapping concerns and potential avenues of failure.

There were 2 DR's that came from this, one abandoned, and one ongoing
- Abandoned (too many choices) : https://github.com/OpenAssetIO/OpenAssetIO/pull/1254
- Ongoing : https://github.com/OpenAssetIO/OpenAssetIO/pull/1267

Work continues in https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/83
