### ISSUE TITLE
Update MC to use `openassetio` from PyPI

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-MediaCreation#9]
## What

Update the project to use `openassetio` from PyPI:
- `setup.py` dependency (+migrate to `pyproject.toml`)
- Docs

## Why

Manual build/installation is no longer needed

## Notes

This will require #10  to be done first.

**Comment by elliotcmorris** [comment]
After discussion with @feltech , decided we're going to do this task first in the update effort, updating the hand rolled traits to modern openassetio, before embarking on #10 to autogenerate them.
